export const LodgesData = [
    {
        "Name": "Brotherhood of the Crossed Swords",
        "Tribes": "All",
        "Description": "South American lodge dedicated to accumulating wealth and power, as well as connections to change the world.",
        "Requirements": "Glory ••; Politics ••; Resources ••; Presence or Composure ••; Contacts (Criminal or Governmental) •••",
        "Benefits": "+• Resources (max of •••••); may purchase Contacts and Allies in their sphere of influence at half cost",
        "Book": "Blas 90"
    },
    {
        "Name": "Cult of Bones",
        "Tribes": "All",
        "Description": "A Pure lodge of explorers, archaeologists, and necromancers, they believe that fragments of Father Wolf are still out there to be found, and they seek them in the hopes of uniting all who are truly loyal to him.",
        "Requirements": "Resolve ••; Composure ••; Occult ••; Pure tribe",
        "Benefits": "May purchase Death gifts as affinity; Cult Talisman fetish",
        "Book": "LodgF 120"
    },
    {
        "Name": "The Eigner Lodge",
        "Tribes": "All",
        "Description": "Viennese clinic that focuses on dream and vision analysis",
        "Requirements": "Cahalith; Academics •••; Science or Medicine •••; Wisdom •",
        "Benefits": "Prophetic Dream ability becomes Teamwork roll; Bonus Medicine specialty in Psychoanalysis",
        "Book": "SotM 134"
    },
    {
        "Name": "Eiwaz Mot",
        "Tribes": "All",
        "Description": "A group of supremacists with a criminal network backing them. Known for stretching the tenets of the Moon.",
        "Requirements": "Strength or Manipulation (for leaders) •••",
        "Benefits": "May purchase Brawl, Firearms, and Larceny for new dots x2; +2 to rolls dealing with spirits of desperation, hate, and pain; leaders may purchase Dominance and Inspiration gifts as affinity gifts",
        "Book": "Blas 106"
    },
    {
        "Name": "El Sacrificio",
        "Tribes": "All",
        "Description": "Aztec-descended werewolves who practice rites of human sacrifice.",
        "Requirements": "Native Aztecs; Honor •••; Stealth ••",
        "Benefits": "Anyone who physically harms a member of the lodge suffer a -1 penalty to all rolls for three days; may learn Stealth Gifts as tribal gifts.",
        "Book": "SoM 105"
    },
    {
        "Name": "Lodge of the Black Woods",
        "Tribes": "All",
        "Description": "A large co-operative of People near Germany's Black Forest, presided over by this Lodge. Formed after the dissarray of WWII.",
        "Requirements": "Harmony 4",
        "Benefits": "+1 to all Social rolls with other lodge members, including Resolve + Composure to resist Death Rage",
        "Book": "LodgS 37"
    },
    {
        "Name": "Lodge of the Boundary",
        "Tribes": "All",
        "Description": "Help lingering ghosts pass to the great beyond",
        "Requirements": "Elodoth; Academics •, Occult ••, Investigation •",
        "Benefits": "Death Gifts count as affinity; may use Elodoth's Auspice Ability on ghosts",
        "Book": "SotM 98"
    },
    {
        "Name": "Lodge of the Broken Pledge",
        "Tribes": "All",
        "Description": "Destroy spirit cults; sever deals between spirits and mortals",
        "Requirements": "Ithaeur; Wisdom ••; Rituals •••",
        "Benefits": "Add Wisdom Renown to Gift or rite rolls to break a spirit's control over mortals, double if power already uses Wisdom",
        "Book": "SotM 64"
    },
    {
        "Name": "Lodge of the Crossroads",
        "Tribes": "All",
        "Description": "An American lodge that looks into the particular spirits that are generated by the negative aspects of American culture. This is supposed to reinforce the positive themes of a local culture.",
        "Requirements": "Cunning ••; Investigation •; Occult ••",
        "Benefits": "Contacts (cryptozoologists), (legend trippers), (conspiracy theorists), and (folklore occultists) • each; may purchase Investigation, Occult, and Stealth for new dots x2",
        "Book": "Blas 86"
    },
    {
        "Name": "Lodge of the Coyote",
        "Tribes": "All",
        "Description": "A south-western and central American lodge recently spread to south-east asian, focused on smuggling people across boarders.",
        "Requirements": "Cunning ••, Wits ••, Stealth or Subterfuge •",
        "Benefits": "Allies, Contacts, and Status among Uratha Society XP cost x1 instead of x2. Gain Stealth Gifts as affinity.",
        "Book": "SoM 44"
    },
    {
        "Name": "Lodge of Echoes",
        "Tribes": "All",
        "Description": "A British Lodge dedicated to learning the lessons from the long history of wars in the nation.",
        "Requirements": "Academics •; particular Academics specialty in an ancient British culture; Glory •; Honor •",
        "Benefits": "May purchase Academics, Brawl, and Weaponry at new dots x2; may inherit a fetish",
        "Book": "SotUK 73"
    },
    {
        "Name": "Lodge of the Endless Horizon",
        "Tribes": "All",
        "Description": "Explorers of the Gurihal, the physical world",
        "Requirements": "Irraka; Athletics •••; Survival •••, Specialties in 3 different environments",
        "Benefits": "+1 bonus to Streetwise and Survival rolls; May purchase Knowledge Gifts as affinity",
        "Book": "SotM 27"
    },
    {
        "Name": "Lodge of the Endless Moon",
        "Tribes": "All",
        "Description": "An East Asian lodge that beleive a more mortal oriented version of the usual Pangea myth, in which Luna is male, and that they should not just police spirits, but respect those that know their place.",
        "Requirements": "Glory •; Wisdom •; Purity •; Honor •; Willpower ••••• •",
        "Benefits": "May purchase Honor the Benevolent Spirit rite; +1 Persuasion and +2 Intimidation to social dealings with spirits that know about the lodge and recognize the member to be one; may purchase Willpower for 5 xp; gain +• Honor free",
        "Book": "LodgS 43"
    },
    {
        "Name": "Lodge of the Fallen Idol",
        "Tribes": "All",
        "Description": "A group arising from the annihilated Lodge of the Hidden Idol. They beleive humanity's spirituality to be dangerous and that all unprovable beliefs should the quashed.",
        "Requirements": "Academics ••",
        "Benefits": "+2 to defend against attacks that make a member doubt their cause or look to an unprovable supernatural explanation; +1 to Social rolls to make someone question their faith; -1 penalty (minimum 2 dice) on all Harmony checks",
        "Book": "LodgS 49"
    },
    {
        "Name": "Lodge of the Feast",
        "Tribes": "All",
        "Description": "A lodge united by their feasting upon human flesh, one and all.",
        "Requirements": "Rituals ••",
        "Benefits": "May spend a Willpower point to resist degeneration for eating human flesh. Communion of the Flesh rite",
        "Book": "LodgF 124"
    },
    {
        "Name": "Lodge of Fevered Light",
        "Tribes": "All",
        "Description": "A lodge hiding behind a strange Church of the Lighthouse, which, amongs altruistic goals, asks to distrust technology and medicine. At higher levels, it seeks to spread the 'purifying' power of disease.",
        "Requirements": "Cunning •; Glory •",
        "Benefits": "May purchase Fever gifts",
        "Book": "Blas 81"
    },
    {
        "Name": "Lodge of the Firestick",
        "Tribes": "All",
        "Description": "A populous Australian lodge that protects areas from fire, as well as harnessing it.",
        "Requirements": "Occult •; Survival ••",
        "Benefits": "Any attempt to make fire will succeed; fire always behaves as expected; gain +4 to set or guide a destructive fire; gain +2 to rolls for gifts to summon or govern fire; may purchase Firestick gifts",
        "Book": "LodgS 56"
    },
    {
        "Name": "Lodge of the Fury Choir",
        "Tribes": "All",
        "Description": "Seekers of true Purity who yearn to become Ralunim",
        "Requirements": "Rahu; Purity •••; 5 dots spread between Brawl, Firearms, or Weaponry; Harmony 7+",
        "Benefits": "Can get extra time in Gauru; Fury Choir Fighting Style",
        "Book": "SotM 173"
    },
    {
        "Name": "Lodge of the Grotto",
        "Tribes": "All",
        "Description": "A curious and ill-reputed lodge whose members prefer to live underground, away from the night sky, they are infamous for their hermetic and unnerving behaviors.",
        "Requirements": "Survival (Underground) specialty",
        "Benefits": "Grants a significant bonus to hunt targets underground; may purchase Grotto gifts as affinity.",
        "Book": "LodgF 128"
    },
    {
        "Name": "The Lodge of the Hazzan",
        "Tribes": "All",
        "Description": "Lorekeeping Jewish werewolves who help interpret the Torah in line with Uratha culture and condition",
        "Requirements": "Cahalith of Jewish descent; Expression •, Academics ••, Specialty in Torah or Rabbinical Studies; Status: Jewish Community •",
        "Benefits": "Can learn Rite of Laila's message; 9-again on Occult rolls involving Jewish mysticism",
        "Book": "SotM 137"
    },
    {
        "Name": "Lodge of the Hunt",
        "Tribes": "All",
        "Description": "A lodge brought together in the pursuit of tracking down a particular foe or group of foes, afterwords the group dissolves.",
        "Requirements": "None (save hate for the enemy)",
        "Benefits": "Allegiance to a powerful spirit of the hunt, which does not tolerate activities outside of pursuit.",
        "Book": "WtF 203"
    },
    {
        "Name": "Lodge of Kletby",
        "Tribes": "All",
        "Description": "A small lodge focused in the Czech Republic. They study curses, specifically the curse of Father Wolf.",
        "Requirements": "Occult ••; Wisdom ••; Rituals ••",
        "Benefits": "Gain Invoke Kletba rite free",
        "Book": "LodgS 77"
    },
    {
        "Name": "Lodge of the Lake",
        "Tribes": "All",
        "Description": "A localized Lodge that watches the sinister Lake Vostok in Antarctica, the largest unpoiled freshwater source in the world, and the mysterious sublime inhabitant of its waters.",
        "Requirements": "Harmony 6 or less",
        "Benefits": "May purchase Social attributes for new dots x4; may purchase Social skills for new dots x2; one free Dominance gift",
        "Book": "LodgS 83"
    },
    {
        "Name": "Lodge of London",
        "Tribes": "All",
        "Description": "An overarching lodge linked to the spirit of London, who take some members of those packs of London to add the influence of London to their engagements with spirits.",
        "Requirements": "Must live in London",
        "Benefits": "May purchase Eyes of the City rite; +2 to all Survival and Tracking rolls in the city; +1 to Negotiation rolls with naturally occurring urban spirits",
        "Book": "SotUK 80"
    },
    {
        "Name": "Lodge of the Lost",
        "Tribes": "All",
        "Description": "A lodge with a lost purpose, having defeated the 'Great Darkness' in 1998, the remaining members are focused near the medditerrainean, and are 'dead' when it comes to seeing their future.",
        "Requirements": "None",
        "Benefits": "Any attempt to divine, prophesize, scry, or discern the future of a member automatically fail (if a dramatic failure is rolled, no information will be given, even false or misleading), nor can the member use such abilities, and their use on another that would include the member omit or rewrite that element, even if the member should leave the lodge",
        "Book": "LodgS 91"
    },
    {
        "Name": "Lodge of Luna’s Devotees",
        "Tribes": "All",
        "Description": "A lodge seeking to add new forms to their array. Loose knit and ambitious.",
        "Requirements": "Cunning •; desire to seek other forms",
        "Benefits": "Free skill specialty",
        "Book": "BotW 33"
    },
    {
        "Name": "Lodge of Luna's Tears",
        "Tribes": "All",
        "Description": "Kill the Pure, take their renown",
        "Requirements": "Irraka; Cunning ••••; Stealth ••••; Brawl or Weaponry •••",
        "Benefits": "Tears of Luna scar fetish",
        "Book": "SotM 28"
    },
    {
        "Name": "Lodge of Lycurgus",
        "Tribes": "All",
        "Description": "Bind spirits and werewolves to oaths to maintain order",
        "Requirements": "Elodoth; Politics •, Persuasion •; Honor •••",
        "Benefits": "Use Honor Renown for Elodoth Spirit Envoy ability",
        "Book": "SotM 99"
    },
    {
        "Name": "Lodge of Mammon",
        "Tribes": "All",
        "Description": "A lodge which prizes selfishness and greed above all else.",
        "Requirements": "Cunning •; Subterfuge ••",
        "Benefits": "+1 Resources dot; bonus to social interaction with greed-spirits",
        "Book": "LodgF 132"
    },
    {
        "Name": "Lodge of the Modernist",
        "Tribes": "All",
        "Description": "A lodge with origins in the Bone Shadows that studies the power of words and language.",
        "Requirements": "Academics or Occult •••",
        "Benefits": "+3 to rolls to understand relationship between words; access to the Power in Words Rite",
        "Book": "LodgS 96"
    },
    {
        "Name": "Lodge of Praetors",
        "Tribes": "All",
        "Description": "Self-appointed Guardians of the Oath of the Moon, attempting to redeem the Forsaken by punishing betrayers of the Oath.",
        "Requirements": "Purity •••; Honor ••; Harmony 4",
        "Benefits": "May purchase Insight and Knowledge gifts as affinity gifts; may purchase Empathy, Intimidation, and Persuasion for new dots x2",
        "Book": "SotUK 84"
    },
    {
        "Name": "Lodge of Quetzal",
        "Tribes": "All",
        "Description": "A small South American lodge dedicated to battling the interests of the Brotherhood of the Crossed swords, and discovering their secrets.",
        "Requirements": "Anybeast (Mother Luna ••); Stealth ••; Subterfuge ••",
        "Benefits": "May purchase Stealth and Insight gifts as affinity gifts",
        "Book": "Blas 93"
    },
    {
        "Name": "Lodge of the Red Sands",
        "Tribes": "All",
        "Description": "A lodge linked to the deserts of the world. They seek to survive harsh areas and gain personal power, though phbysical strength and monopolising wellsprings of Essence.",
        "Requirements": "Glory ••; Stamina •••; Survival •••",
        "Benefits": "Animal Ken, Tracking, and Survival may be purchased for new dots x2; may purchase Dominance or Elemental gifts as tribal gifts",
        "Book": "LodgS 102"
    },
    {
        "Name": "Lodge of the Savior",
        "Tribes": "All",
        "Description": "Christian werewolves of many faiths and causes, all are united under the Lord.",
        "Requirements": "Harmony 6; adhere to the Christian faith",
        "Benefits": "Instruction for making a Blood Rosary fetish; bonus to Resolve rolls to resist spirit powers",
        "Book": "LodgF 136"
    },
    {
        "Name": "Lodge of Scars",
        "Tribes": "All",
        "Description": "A lodge of old werewolves, weakened physically, but great in metaphysical power and wisdom.",
        "Requirements": "Must have three or more Renown at •••• or higher; must know at least three ••••• gifts",
        "Benefits": "May purchase Dominance, Inspiration, and Rage gifts as tribal gifts; Persuasion, Intimidation, and Politics (Uratha) may be purchased for new dots x2; scar fetishes cost • less than normal; new members receive ••• of Renown to distribute according to their Last Mile",
        "Book": "LodgS 113"
    },
    {
        "Name": "Lodge of Scavengers",
        "Tribes": "All",
        "Description": "A lodge localized in the UK that accepts the destiute and poor, and are dedicated to surviving their poor station.",
        "Requirements": "Survival (urban) specialty; Streetwise ••; Cunning ••; Purity •",
        "Benefits": "May purchase Drive, Survival, Streetwise, and Subterfuge for new dots x2; may purchase Stealth and Technology gifts as affinity gifts",
        "Book": "SotUK 87"
    },
    {
        "Name": "Lodge of the Second Moonrise",
        "Tribes": "All",
        "Description": "Redemptive Uratha who want to become reborn as Rahu",
        "Requirements": "Purity •",
        "Benefits": "Strength or Dominance Gifts as affinity",
        "Book": "SotM 175"
    },
    {
        "Name": "Lodge of the Shadow Throne",
        "Tribes": "All",
        "Description": "Encourage Forsaken ruling over the Shadow as Kings",
        "Requirements": "Ithaeur; Wisdom • or Honor ••; Politics •",
        "Benefits": "Learn Dominance Gifts as affinity, use Dominance Gifts on spirits. +2 to mundane rolls to intimidate or command spirits",
        "Book": "SotM 63"
    },
    {
        "Name": "Lodge of the Shepherd",
        "Tribes": "All",
        "Description": "A lodge dedicated to protecting humans and its members families. Usually looked down upon.",
        "Requirements": "Purity •; Harmony 7",
        "Benefits": "May recognize wolf-blooded and other lodge members on sight automatically; may purchase Banish Human, Shared Scent, Banish Spirit, Fortify the Border Marches, and Rite of Moon's Love rites for half cost",
        "Book": "BotW 106"
    },
    {
        "Name": "Lodge of Silence",
        "Tribes": "All",
        "Description": "A lodge dedicated to preserving the secret of the People within prisons, dedicated not to escape, but to remain.",
        "Requirements": "Must have been imprisoned for an extended period of time",
        "Benefits": "+2 to resist Death Rage outside combat; +2 to resist Intimidation; +1 to grapple checks",
        "Book": "BotW 73"
    },
    {
        "Name": "Lodge of Songkran",
        "Tribes": "All",
        "Description": "A local lodge from Southeast Asia dedicated to bringing the jungle back from is mad state to its former glory.",
        "Requirements": "Empathy ••; Purity •••; Harmony 6",
        "Benefits": "+2 to Composure rolls to resist Kuruth; Harmony purchases are 2xp cheaper; Call Water gift free; may share 1 WP with another member per day",
        "Book": "LodgS 117"
    },
    {
        "Name": "Lodge of the Spirit Chains",
        "Tribes": "All",
        "Description": "Trapping powerful and dangerous spirits into fetishes to be locked away",
        "Requirements": "Ithaeur; Wisdom •••; Cunning ••, must know Bind Spirit and Fetish Rite",
        "Benefits": "Add Wisdom to Harmony when using rites to call, bind, or trap spirits within a fetish, another +2 if adherent knows spirit's ban",
        "Book": "SotM 65"
    },
    {
        "Name": "Lodge of the Spoken Word",
        "Tribes": "All",
        "Description": "City werewolves trying to modernize and find new ways to pass down Uratha lore",
        "Requirements": "Cahalith; Streetwise and Expression •••",
        "Benefits": "Allies: Urban Spirits at half price; Standard of Station fetish",
        "Book": "SotM 139"
    },
    {
        "Name": "Lodge of the Starless Sky",
        "Tribes": "All",
        "Description": "City wolves that watch for more subtle and insidious threats",
        "Requirements": "Rahu; Purity ••; Stealth and Streetwise •••",
        "Benefits": "Alteration to Warrior's Eye Auspice ability; Add Knowledge or Stealth to Affinity Gifts",
        "Book": "SotM 177"
    },
    {
        "Name": "Lodge of the Storm’s Eye",
        "Tribes": "All",
        "Description": "A lodge with ancient binding magic that seeks to find the biggest, baddest spirits in the Shadow and bind them to their will.",
        "Requirements": "Must be Ithaeur",
        "Benefits": "+2 on Fetish Rite roll sot create Condor Idols; may purchase the Shackle Spirit rite; may purchase Occult and Survival at new dots x2",
        "Book": "LodgS 122"
    },
    {
        "Name": "Lodge of the Thin Shadow",
        "Tribes": "All",
        "Description": "A lodge dedicated to protecting others, hiding them from conflict. Highly secret.",
        "Requirements": "••••• ••• combined in Larceny and Stealth; Streetwise •",
        "Benefits": "May make information secret in such a way that it can never be revealed by any means to non-members; may purchase Stealth gifts",
        "Book": "LodgS 127"
    },
    {
        "Name": "Lodge of the Union",
        "Tribes": "All",
        "Description": "A lodge that seeks to unify everything in the long run, but encourages cooperation between Uratha in the meantime.",
        "Requirements": "Harmony 5",
        "Benefits": "Mystic sigil that grants +2 to Social rolls with beings in the Hisil that are impressed by diplomats or fairness, visible in the physical world only to other members",
        "Book": "LodgS 134"
    },
    {
        "Name": "Lodge of Unity",
        "Tribes": "All",
        "Description": "Dedicated to pursuing unification and peace between all of the Forsaken, believing this the only path to victory over the Pure.",
        "Requirements": "Cunning or Honor ••; Brawl, Weaponry, or Persuasion •••; Harmony 6",
        "Benefits": "XP cost reduction for Brawl, Weaponry, Persuasion, and Intimidation; Instruction for the creation of Truth-Catcher fetishes.",
        "Book": "LodgF 140"
    },
    {
        "Name": "Lodge of the Willow Branch",
        "Tribes": "All",
        "Description": "A lodge dedicated to destroying vampires, seeing them as an imbalance in the Shadow.",
        "Requirements": "Cunning •; Glory •; Weaponry ••",
        "Benefits": "+2 to resist a vampire's supernatural mind-manipulation powers; may craft Willow Stake fetish",
        "Book": "LodgS 140"
    },
    {
        "Name": "The Secret Tribunal",
        "Tribes": "All",
        "Description": "Secret judge, jury, and punishers for Oath of the Moon oathbreakers",
        "Requirements": "Elodoth; Investigation •• (to discern the truth); Empathy ••, Streetwise • (to determine fitting message-sending punishment)",
        "Benefits": "Two dots for Allies (Local Werewolves), Contacts (Local Werewolves), or Contacts (Local Spirits); Investigation and Subterfuge Experience cost reduction",
        "Book": "SotM 101"
    },
    {
        "Name": "Valkyrja Mot",
        "Tribes": "All",
        "Description": "A group of leaders that provide great pressure in resolving conflicts. Closely aligned to Norse mythology.",
        "Requirements": "Strength or Dexterity •••; Brawl ••; Weaponry •••; Purity ••; Glory ••; must be female",
        "Benefits": "Gain a minor klaive (spear or sword) free; may purchase Death and Inspiration gifts as affinity gifts; altered version of Funeral Rite",
        "Book": "Blas 101"
    },
    {
        "Name": "Lodge of Cerberus",
        "Tribes": "Blood Talons",
        "Description": "Walkers between the world of the living and the dead, and destroys of all ghosts.",
        "Requirements": "Harmony 7; Glory ••; Purity ••; Brawl or Weaponry •••; Rituals ••",
        "Benefits": "Speak with the Guardian Rite; Instruction for making Wraith-Claw fetishes; Death gifts purchased at affinity cost",
        "Book": "LodgF 37"
    },
    {
        "Name": "Lodge of the Einherjar",
        "Tribes": "Blood Talons",
        "Description": "Dedicated to discovering the fate of destroyed and decimated packs.",
        "Requirements": "Glory ••; Honor •; Investigation ••",
        "Benefits": "May purchase Insight gifts as tribal gifts; may substitute Glory for Honor when using the Echo Dream gift or for Purity when using the Soul Read gift; free Occult specialty in Uratha Lore",
        "Book": "Tribes 32"
    },
    {
        "Name": "Lodge of Garm",
        "Tribes": "Blood Talons",
        "Description": "Skilled leaders, the embodiment of perfection in battle.",
        "Requirements": "Harmony 7; Glory ••; Brawl, Weaponry, or Firearms ••••",
        "Benefits": "Small fetish; reduced XP for Brawl, Weaponry, Athletics, and Persuasion",
        "Book": "WtF 199, LodgF 53"
    },
    {
        "Name": "Lodge of Night",
        "Tribes": "Blood Talons",
        "Description": "Hunters of the Shadow Realm, they choose to serve as the first line of defense against the most horrific entities from that dark place, and they do so with utmost tenacity and determination.",
        "Requirements": "Brawl or Weaponry ••••; Glory ••; Willpower 7",
        "Benefits": "Perfect vision in any lighting; Ability to purchase Rite of the Ghost Howl; XP cost of Brawl, Occult, and Athletics reduced; can spend a willpower point to inflict a penalty on all enemy defenses for the rest of the scene. Penalty to Harmony rolls at night.",
        "Book": "LodgF 73"
    },
    {
        "Name": "Lodge of the Lone Wolf",
        "Tribes": "Blood Talons",
        "Description": "A lodge for those who no longer are part of a pack, or never were. Supposedly watched over by the Fifth child of Father Wolf, who was supposedly driven out for being the runt.",
        "Requirements": "Cannot be a member of a pack",
        "Benefits": "+• of Survival; +1 on Perception (Wits + Composure)",
        "Book": "Tribes 37"
    },
    {
        "Name": "Lodge of the Rose",
        "Tribes": "Blood Talons",
        "Description": "Dedicated to a code of chivalry to harmonize savagery and civility, adhering to Oaths fanatically.",
        "Requirements": "Glory ••; Honor •••",
        "Benefits": "+2 to resist supernatural powers that would force the breaking of a vow sealed by Oath of the Rose rite, -2 to opponent if not contested; reflexive Wits + Composure to know if an action will violate such an Oath; -1 penalty to Harmony checks made as a result of a broken vow",
        "Book": "LodgS 107"
    },
    {
        "Name": "Lodge of the Shield",
        "Tribes": "Blood Talons",
        "Description": "A small LA lodge with its members in the police force. They help shape the force and cover for their peers.",
        "Requirements": "Honor •; Investigation •••; Status(Police) •",
        "Benefits": "+1 bonus to resist Death Rage; may buy Status (Police) and Fighting Style (Police Tactics) at half cost",
        "Book": "Tribes 34"
    },
    {
        "Name": "Lodge of Swords",
        "Tribes": "Blood Talons",
        "Description": "Often known as \"Crusaders\", this Lodge has its members each dedicated to a single cause or fight to which they are wholly and passionately given over to.",
        "Requirements": "Resolve •••; Brawl, Weaponry, or Firearms •••; Glory ••; Purity ••; Willpower 6",
        "Benefits": "Packstone, possibly a Mercy Gem; XP cost reduction for Brawl, Weaponry, Intimidation, and Persuasion",
        "Book": "LodgF 97"
    },
    {
        "Name": "Lodge of Wendigo",
        "Tribes": "Blood Talons",
        "Description": "Masters of stealth, infiltration, and the cautious, silent hunt.",
        "Requirements": "Glory ••; must make a positive impression on the lodge's totem spirit",
        "Benefits": "May purchase Rite of Blood's Revelation and Rite of the Forbidden Flesh; reduced XP cost to purchase Athletics, Stealth, and Survival.",
        "Book": "LodgF 106"
    },
    {
        "Name": "Lodge of Doors",
        "Tribes": "Bone Shadows",
        "Description": "Seekers of mysteries and destroyers of barriers.",
        "Requirements": "Harmony 6; Cunning ••; Larceny or Investigation ••",
        "Benefits": "May purchase Opening gifts as if they were tribal gifts.",
        "Book": "LodgF 49"
    },
    {
        "Name": "Lodge of Death",
        "Tribes": "Bone Shadows",
        "Description": "A large lodge which studies death in all its aspects, it holds a deep reverence for the significance of death.",
        "Requirements": "Honor •; Wisdom •••; Occult ••• with specialty in Ghosts, Death, or similar",
        "Benefits": "Members are imbued with knowledge of their time of death. Immunity to fear. Harmony is treated as two higher for Death Rage.",
        "Book": "LodgF 45"
    },
    {
        "Name": "Lodge of Harbingers",
        "Tribes": "Bone Shadows",
        "Description": "Messengers and harbingers of omens, their wisdom is greatly valued.",
        "Requirements": "Cunning or Wisdom •; Athletics ••; Stealth ••",
        "Benefits": "May learn Stealth gifts as Tribal gifts; gains a dice modifier to deal favorably with other Forsaken.",
        "Book": "WtF 200, LodgF 57"
    },
    {
        "Name": "Lodge of the Hallowed Halls",
        "Tribes": "Bone Shadows",
        "Description": "A group of highly learned wolves who seek to maintina ties with mortal academia.",
        "Requirements": "Academics ••; Wisdom ••; Cunning •; Subterfuge •; First Tongue merit",
        "Benefits": "Resources ••; Contacts (Lodge of the Hallowed Halls); may purchase Subterfuge, Socialize, and Persuasion at new dots x2",
        "Book": "Tribes 66"
    },
    {
        "Name": "Lodge of the Hundred Days",
        "Tribes": "Bone Shadows",
        "Description": "A Rwandan lodge dedicated to dealing with the supernatural repercussions of the genocide..",
        "Requirements": "Honor••; Wisdom••; Stealth••; Harmony 7",
        "Benefits": "Free specialty in any one skill; free Gauntlet Cloak gift; may purchase Stealth gifts as tribal gifts",
        "Book": "Tribes 64"
    },
    {
        "Name": "Lodge of the Hungry Ghosts",
        "Tribes": "Bone Shadows",
        "Description": "A Japanese originating lodge that seeks to unravel the causes of a spirits discontent rather than simply punishing. They unfortuanly have a poor reputation with others, as they sometimes defend aggressive spirits and other enemies of the People.",
        "Requirements": "Primal Urge •••; Wisdom ••; Harmony 5 to 7",
        "Benefits": "May take 1 additional Essence when drawing from loci; +1 to cross the Gauntlet while looking into a reflective surface",
        "Book": "LodgS 64"
    },
    {
        "Name": "Lodge of Mania",
        "Tribes": "Bone Shadows",
        "Description": "A cult that seeks prophetic powers, weilding madness as a tool for power, but are usually shunned by others.",
        "Requirements": "Cunning ••; Glory ••must have a derangement due to Harmony loss",
        "Benefits": "+1 to all Animal Ken and Persuasion rolls; may spend a standard action to grand a +2 bonus to a packmate's Resolve + Composure roll to come out of Death Rage; learn Rite of the Maenads free; -1 to Harmony check to resist gaining a derangement",
        "Book": "Blas 77"
    },
    {
        "Name": "Lodge of Prophecy",
        "Tribes": "Bone Shadows",
        "Description": "Quite possibly the most ancient lodge, this group seeks to peer into the future however possible, believing that the battles in the future are the only ones not yet decided.",
        "Requirements": "Harmony 7; Wisdom ••••; Occult ••••; Know the following rites: Bind Spirit, Call Gaffling, Call Jaggling, Wake the Spirit",
        "Benefits": "Knowledge gifts treated as tribal; Omen Gazing gift at five XP cost reduction; may purchase Prophet's Voice merit",
        "Book": "LodgF 77"
    },
    {
        "Name": "Lodge of the Reaping",
        "Tribes": "Bone Shadows",
        "Description": "A lodge that allows for the consumption of human flesh, on the proviso that they remove the soul of the human, and that they take useless or near death humans.",
        "Requirements": "None",
        "Benefits": "Free rites to store human souls; death-spirit guardian; +2 to see or reach across the Gauntlet; +3 to all rolls to notice spirits or spirit activity",
        "Book": "Tribes 69"
    },
    {
        "Name": "Lodge of Voices",
        "Tribes": "Bone Shadows",
        "Description": "Believers that all werewolves live on after death in the form of ancestors spirits, this lodge is dedicated to seeking out these spirits and utilizing their wisdom.",
        "Requirements": "Language (First Tongue) merit; Wisdom ••; Purity •; Occult ••; Rituals •",
        "Benefits": "Access to the Ancestral Vessel merit; free Academics (Uratha History) specialty",
        "Book": "LodgF 103"
    },
    {
        "Name": "Lodge of Absolution",
        "Tribes": "Fire-Touched",
        "Description": "Believers that all sins are forgivable, these pious and amoral wolves frequently perform many sins in pursuit of their private interests, and their Harmony and sanity frequently reflects this.",
        "Requirements": "Resolve •••; Stamina •••, Rite of Penance.",
        "Benefits": "Choose three skills which can now be acquired at New Dots x 2. Gifts cannot be learned without raising Renown.",
        "Book": "Pure 62"
    },
    {
        "Name": "Lodge of Plague",
        "Tribes": "Fire-Touched",
        "Description": "Believers that ideas can spread as diseases, these hounds seek to proselytize their faith, all the while spreading filth to all they touch.",
        "Requirements": "Wisdom •; know at least one Disease Gift",
        "Benefits": "Iron Stamina •• Merit",
        "Book": "Pure 61"
    },
    {
        "Name": "Armée Sauvage, The",
        "Tribes": "Ghost Wolves",
        "Description": "A group of independants that try to resolve the effects of wars throughout the world, fighting rather than hiding from the grand battles.",
        "Requirements": "Honor •••; Harmony 6 or higher; Ghost Wolf",
        "Benefits": "May choose Inspiration, Dominance, or Warding gifts to learn as tribal gifts",
        "Book": "LodgS 11"
    },
    {
        "Name": "Brotherhood of Eshu’s Cap",
        "Tribes": "Hunters in Darkness",
        "Description": "Tricksters that sow chaos in the ranks of those threatening the sacred places of the world.",
        "Requirements": "Cunning •••; Purity •; Larceny ••; Stealth ••",
        "Benefits": "+1 to appropriate Social rolls when defending a sacred place or object; may purchase Warding gifts as tribal gifts",
        "Book": "LodgS 18"
    },
    {
        "Name": "Lodge of Arkadia",
        "Tribes": "Hunters in Darkness",
        "Description": "A group that seeks major self-evaluation as the key to strength, being honest about their failings and correcting the sin of pride the People are often guilty of. They are seen as soft.",
        "Requirements": "Honor •; Purity •; Academics •; one Academics specialty; Animal Ken ••; Survival ••",
        "Benefits": "May purchase Academics, Animal Ken, Empathy, and Survival for new dots x2; +1 to bite attacks and Defense",
        "Book": "Blas 74"
    },
    {
        "Name": "Lodge of Ashes",
        "Tribes": "Hunters in Darkness",
        "Description": "Believers that the Uratha have lost their way and failed in their duties, and they seek to free the captive spirits that their fellows have bound.",
        "Requirements": "Harmony 8; Primal Urge •••; Purity •••••; Rite of Contrition",
        "Benefits": "Chain-Breaker merit",
        "Book": "LodgF 33"
    },
    {
        "Name": "Lodge of Carrion",
        "Tribes": "Hunters in Darkness",
        "Description": "A group of immensly practical Hunters. They are conservative with their ideas of what is sacred and worth protecting, and will abandon those things for practical purposes should a site have outlasted its usefulness.",
        "Requirements": "Cunning •; Survival ••; Stamina ••",
        "Benefits": "Iron Stomach merit; +2 on rolls to glean information or resources from an area or source that's been inspected already; +2 to foraging rolls",
        "Book": "Tribes 102"
    },
    {
        "Name": "Lodge of the Empty Den",
        "Tribes": "Hunters in Darkness",
        "Description": "A small North American lodge dedicated to protecting children in all forms, but in particular supernatural enemies.",
        "Requirements": "Purity •; Honor •; Empathy •••",
        "Benefits": "May learn Insight gifts as tribal gifts; +1 to avoid Death Rage (-3 instead if trigger is the death of a child)",
        "Book": "Tribes 100"
    },
    {
        "Name": "Lodge of Harmony",
        "Tribes": "Hunters in Darkness",
        "Description": "An immense lodge who seek to protect their territories from humans, aid fellow werewolves, and ensure that hidden dangers remain buried.",
        "Requirements": "Harmony 7; Purity •••; Wisdom •",
        "Benefits": "May purchase Warding gifts as though they were tribal. May learn the Harmony rites.",
        "Book": "LodgF 60"
    },
    {
        "Name": "Lodge of Howling Death",
        "Tribes": "Hunters in Darkness",
        "Description": "A lodge in the UK dedicated to fighting the Pure and letting them know exactly who their dealing with.",
        "Requirements": "Harmony 4; Purity ••; Willpower ••••• •; Survival •; Brawl •",
        "Benefits": "May purchase Survival, Intimidation, and Brawl for new dots x2; gain free Death Howl Stone fetish; may purchase Stealth and Nature gifts as affinity gifts",
        "Book": "SotUK 76"
    },
    {
        "Name": "Lodge of Ruin",
        "Tribes": "Hunters in Darkness",
        "Description": "An existential brotherhood who acknowledges the inevitable end of all things, and thus maintain little concern for temporal and passing affairs.",
        "Requirements": "Craft, Computer, or Drive ••; Cunning ••; Survival ••",
        "Benefits": "Shaping gifts may be learned as Tribal; reduced XP cost for Intimidation, Streetwise, and Survival",
        "Book": "LodgF 81"
    },
    {
        "Name": "Lodge of Seasons",
        "Tribes": "Hunters in Darkness",
        "Description": "An unusual lodge whose temperament varies with the season,",
        "Requirements": "Purity •••",
        "Benefits": "Gains a class of gifts as Tribal favored, one of Weather, Rage, Insight, or Death",
        "Book": "WtF 201, LodgF 91"
    },
    {
        "Name": "Lodge of the Sleeping Bear",
        "Tribes": "Hunters in Darkness",
        "Description": "A local lodge to the Michigan area, occupying a vaccum left by a major war between the Pure and Forsaken.",
        "Requirements": "Must remain in the area around Lake Michigan",
        "Benefits": "Anything learned from other members is 25% cheaper",
        "Book": "Tribes 104"
    },
    {
        "Name": "Lodge of Wrath",
        "Tribes": "Hunters in Darkness",
        "Description": "Bloody defenders of their territories, members of this lodge exact revenge upon all trespassers.",
        "Requirements": "Purity ••; Honor ••; Brawl or Weaponry ••; Survival ••",
        "Benefits": "May learn Retribution gifts as affinity.",
        "Book": "LodgF 114"
    },
    {
        "Name": "Lodge of 66",
        "Tribes": "Iron Masters",
        "Description": "A local lodge linked to the health of Route 66's spirit ecology as it decays.",
        "Requirements": "Glory ••; Honor ••; Crafts ••; must own a \"proper\" vehicle",
        "Benefits": "+1 on Crafts rolls to repair or modify items; may purchase Physical attributes at new dots x4",
        "Book": "LodgS 31"
    },
    {
        "Name": "Lodge of Arms",
        "Tribes": "Iron Masters",
        "Description": "A lodge dedicated to the use and mastery of human weapons, who are deeply attached to their personal arms.",
        "Requirements": "Occult ••; Firearms or Weaponry •••",
        "Benefits": "Bound weapon gets a significant bonus to all attack rolls; related skill is treated as one dot higher for all use of the same type of weapon.",
        "Book": "LodgF 30"
    },
    {
        "Name": "Lodge of Chemics",
        "Tribes": "Iron Masters",
        "Description": "A small lodge of scientists that seek to understand the specifics of tthe werewolf condition, be it shapeshifting, regeneration or anythign else.",
        "Requirements": "Cunning •; Science (Chemistry) ••; Medicine ••",
        "Benefits": "+1 to resist the adverse effects of drugs; may purchase Medicine and Science for new dots x2",
        "Book": "BotW 26"
    },
    {
        "Name": "Lodge of the Hidden Hunt",
        "Tribes": "Iron Masters",
        "Description": "A group that seeks to keep themselves hidden from their targets, maintaining their human identities.",
        "Requirements": "Cunning ••; Persuasion ••; Subterfuge •••, Resources ••; cannot raise Harmony while a member",
        "Benefits": "Ignore up to -3 of Primal Urge social penalties with humans; gain +3 to resist supernatural powers that would show them to be anything but normal humans",
        "Book": "Tribes 139"
    },
    {
        "Name": "Lodge of Ilia",
        "Tribes": "Iron Masters",
        "Description": "A lodge that specializes in maintaing vigil within urban areas.",
        "Requirements": "Streetwise •",
        "Benefits": "+1 on rolls that support the \"theme\" of a city if known",
        "Book": "LodgS 71"
    },
    {
        "Name": "Lodge of Lightning",
        "Tribes": "Iron Masters",
        "Description": "Terrifying and extraordinarily driven werewolves that are renowned for their mad ingenuity.",
        "Requirements": "Cunning ••; Wits •••",
        "Benefits": "Gains a dice modifier to avoid knockdown; learn Weather gifts as if it were Tribal.",
        "Book": "WtF 202, LodgF 63"
    },
    {
        "Name": "Lodge of Metal",
        "Tribes": "Iron Masters",
        "Description": "A highly respected and ancient Lodge with a penchant for smithing and forging of all types.",
        "Requirements": "Crafts •••; Investigation ••; Wits ••",
        "Benefits": "Gain a significant bonus to all Craft rolls, and a decent one to appease spirits with self-made offerings.",
        "Book": "LodgF 70"
    },
    {
        "Name": "Lodge of Scrolls",
        "Tribes": "Iron Masters",
        "Description": "Loremasters and record keepers of the Uratha.",
        "Requirements": "Intelligence •••; Academics ••; Investigation ••",
        "Benefits": "Gains a bonus whenever researching information; XP cost to advance all mental skills reduced.",
        "Book": "LodgF 88"
    },
    {
        "Name": "Lodge of Spires",
        "Tribes": "Iron Masters",
        "Description": "A lodge about seeing the city and becoming the perfect urban hunters. Aka \"Lodge of the Goddam Batman\"",
        "Requirements": "Glory ••; Wisdom ••; Athletics ••; Stealth •",
        "Benefits": "May purchase City gifts as tribal gifts; may purchase Parkour merit at half cost; may purchase Sacred Vigil rite",
        "Book": "Tribes 141"
    },
    {
        "Name": "Lodge of Stones",
        "Tribes": "Iron Masters",
        "Description": "Denizens of the city and dealers with city-spirits.",
        "Requirements": "Occult •••; Manipulation •••; Empathy ••",
        "Benefits": "Gain ability to contact local city-spirits at will; gains bonus to interacting socially with city and building spirits.",
        "Book": "LodgF 94"
    },
    {
        "Name": "Lodge of Wires",
        "Tribes": "Iron Masters",
        "Description": "Dedicated to preparing the People for the technological changes of the future, as well as dealing with the spirit ecology new technologies provide.",
        "Requirements": "Computers •••; Science ••; Cunning ••; Wisdom •; Primal Urge •••• or less",
        "Benefits": "May buy Information gifts as affinity; may purchase Computer, Politics, and Science skills at new dots x2",
        "Book": "Tribes 136"
    },
    {
        "Name": "Blood of Kings",
        "Tribes": "Ivory Claws",
        "Description": "Claimed to be the descendants of the most ancient royalty and kings, this lodge accepts none who cannot prove the royal nature of their bloodline.",
        "Requirements": "Must be able to prove royal descent",
        "Benefits": "Reduced XP for the Resource merit; reduced XP for learning Politics, Intimidation, Persuasion, Socialize, and Subterfuge",
        "Book": "Pure 84"
    },
    {
        "Name": "Council of Eagles",
        "Tribes": "Ivory Claws",
        "Description": "An ancient lodge that traces back at least to the Roman Senate, these would-be statesmen and leaders are invariably pompous and conservative.",
        "Requirements": "Must be at least 30 years old; Harmony 6; Wisdom ••• or Honor •••",
        "Benefits": "Treat Insight Gifts as affinity; add dice to summon eagle-spirits; reduced XP for learning Investigation and Subterfuge",
        "Book": "Pure 83"
    },
    {
        "Name": "Lodge of Kin’s Blood",
        "Tribes": "Ivory Claws",
        "Description": "Dedicated to tracking down the wolf-blooded and placing them under the protection of the Predator Kings.",
        "Requirements": "Dedication to the cause",
        "Benefits": "-",
        "Book": "Pure 106"
    },
    {
        "Name": "Lodge of Night’s Fear",
        "Tribes": "Ivory Claws",
        "Description": "Explorers of the Shadow Realm, seeking out lost and ancient beings to pry their secrets.",
        "Requirements": "Dedication to the cause",
        "Benefits": "-",
        "Book": "Pure 106"
    },
    {
        "Name": "Lodge of Vermin’s Shadow",
        "Tribes": "Ivory Claws",
        "Description": "Urban scouts and informants, these Uratha often spend their time amongst mortals for the good of their tribe.",
        "Requirements": "Dedication to the cause",
        "Benefits": "-",
        "Book": "Pure 106"
    },
    {
        "Name": "Kshatriyas, The",
        "Tribes": "Storm Lords",
        "Description": "A group of warrior-priests that seek to foster power both in themselves and others, evaluating other packs weaknesses and either fixing them, or putting them down and occupying the territory themselves.",
        "Requirements": "Glory ••; Honor •••;Brawl, Firearms, or Weaponry •••",
        "Benefits": "Fetish Rite free; may craft Staff of the Twice-Born and Sacred Thread fetishes; may ignore unskilled penalty for Social skills",
        "Book": "LodgS 25"
    },
    {
        "Name": "Lodge of the Maelstrom",
        "Tribes": "Storm Lords",
        "Description": "Watchers of coastlines and seas.",
        "Requirements": "Resolve •••; Athletics ••; Occult •",
        "Benefits": "Dice bonus to see things in water; affinity with any water-based Elemental gifts; Sea specialty to Occult roles; Lodge support network",
        "Book": "LodgF 66"
    },
    {
        "Name": "Lodge of Crows",
        "Tribes": "Storm Lords",
        "Description": "Sneaky, manipulative, and utterly ruthless werewolves, who prefer others to do their dirty work for them.",
        "Requirements": "Cunning or Purity ••••",
        "Benefits": "Lodge is extremely protective of members; reduced XP cost to learn Larceny, Stealth, Politics, Persuasion, and Subterfuge.",
        "Book": "WtF 202, LodgF 41"
    },
    {
        "Name": "Lodge of the Final Winter",
        "Tribes": "Storm Lords",
        "Description": "A lodge dedicated to controlling the supposed apocalypse that is due on the world..",
        "Requirements": "Honor ••; Investigation ••; Wits •••",
        "Benefits": "Rite of the Sleeping Seer free; can make Spirit's Dream fetish; +• Wits, Investigation, and Expression; only need 3 hours of sleep per day",
        "Book": "Tribes 172"
    },
    {
        "Name": "Lodge of Salvation",
        "Tribes": "Storm Lords",
        "Description": "Dedicated exclusively to converting the Pure, they operate frequently in secrecy, for both the Pure and their Forsaken brothers do not understand their ways.",
        "Requirements": "Honor •• or Purity ••; Harmony 6",
        "Benefits": "Inspiration gifts may be bought as affinity gifts; receive a bonus to Resolve when resisting gifts used by the Pure; resistance to death rage when wounded by the Pure",
        "Book": "LodgF 84"
    },
    {
        "Name": "Lodge of the Shadow’s Storm",
        "Tribes": "Storm Lords",
        "Description": "A local lodge of California ded icated to keeping the secret of an ancient catastrophy casused by an ambitious Storm Lord.",
        "Requirements": "Storm Lord; must know at least 5 rites",
        "Benefits": "May create Gusuku Headdress fetish; learn Rite of the Ruined Tongue free",
        "Book": "Tribes 176"
    },
    {
        "Name": "Lodge of Thunder",
        "Tribes": "Storm Lords",
        "Description": "Natural leaders who believe that only the most direct, most charismatic, and the most truly powerful have right to command their kind.",
        "Requirements": "Presence •••; Strength or Stamina •••; Glory ••; Honor ••",
        "Benefits": "Inspiration and Strength gifts are treated as affinity.",
        "Book": "LodgF 100"
    },
    {
        "Name": "Lodge of Winter",
        "Tribes": "Storm Lords",
        "Description": "Seekers of power through mystical understanding, and the slow and methodical gathering of knowledge.",
        "Requirements": "Resolve ••; Rituals ••; Wisdom •••",
        "Benefits": "May learn Insight gifts as affinity gifts; taught one free rite of choice upon joining.",
        "Book": "LodgF 110"
    }
]